### PR TITLE
Include PHP xdebug for code-coverage in the builder

### PR DESCRIPTION
**Pull request by rick-nu**
### What

Include PHP xdebug for code-coverage in the builder.

In alphabetic order this time :wink:

### CODE REVIEW

**Comment by rick-nu** [comment]
OK, this is not final yet, seems like you need to define the xdebug module property in your `php.ini` file.

**Comment by rick-nu** [comment]
You can see in https://gitlab.enrise.com/NawCast/NawCast/builds/1779 that it did install the xdebug package, but that phpunit didn't find it yet. Above is the reason why.

**Comment by eXistenZNL** [comment]
Thanks! Also, not in alphabetic order bro, should be above php7-zlib and php7-zip :P

**Comment by rick-nu** [comment]
@eXistenZNL Oh sorry, I first included it without php7 (so it was in alphabetical order), but than prefixed with php7, forgot to move then. Also note that the xdebug module is not yet activated in the php.ini and doesn't do anything yet

**Comment by eXistenZNL** [comment]
Yeah was thinking about that. Nico is in the same situation now in another projects and he includes a xdebug.ini to enable remote debugging etc, but I figured since you only need it for code coverage it should work out of the box since installing it enables it by default :)

**Comment by rick-nu** [comment]
@eXistenZNL I don't think it does enable it by default though. I installed it in https://gitlab.enrise.com/NawCast/NawCast/builds/1779 but it still says a driver could not be found

**Pull request merged**
