### PR TITLE
Add PHP 8.2

### PR DESCRIPTION
**Pull request by Xammie**

### CODE REVIEW

**Comment by eXistenZNL** [comment]
Great, seems to be running just fine :)

Found a few small things, would you mind picking them up?
* Can you rename the Dockerfile to Dockerfile-8.2-edge to denote it is a shorter lived YMMV build?
* Can you update the [version matrix](https://github.com/eXistenZNL/Docker-Builder#version-matrix) in the readme?

**Comment by eXistenZNL** [comment]
Also, sorry for the super late response, I was on holiday and totally missed this :blush:  your work is still very appreciated!

**Comment by Xammie** [comment]
@eXistenZNL Resolved you feedback

**Comment by eXistenZNL** [comment]
Awesome, merged. Thanks!

**Pull request merged**
